[bootstrap.repos]
"~/workspaces/JFenstermacher/herdr-plugin" = { url = "git@github.com:JFenstermacher/herdr-plugin.git", ref = "main" }

[dotfiles]
"~/.config/ghostty" = "ghostty/.config/ghostty"
"~/.config/mise" = { source = "mise/.config/mise", mode = "symlink-each" }
"~/.gitconfig" = "git/.gitconfig"
"~/.gitignore_global" = "git/.gitignore_global"
"~/.config/starship.toml" = "starship/.config/starship.toml"
"~/.config/television" = { source = "television/.config/television", mode = "symlink-each" }
"~/.config/zsh" = "zsh/.config/zsh"
"~/.zshenv" = "zsh/.zshenv"
"~/.config/nvim" = "nvim/.config/nvim"
"~/.config/nvim-writing" = "nvim/.config/nvim-writing"
"~/.config/herdr" = { source = "herdr/.config/herdr", mode = "symlink-each" }
"~/.config/herdr/plugins.json" = { source = "herdr/.config/plugins.json", mode = "template" }
"~/.config/herdr/plugins/dotfiles/herdr-plugin/herdr-plugin.toml" = "herdr/.config/plugins/dotfiles/herdr-plugin/herdr-plugin.toml"
"~/.local/share/mise/plugins/mimiskelda" = { source = "mise/.local/share/plugins/mimiskelda", mode = "symlink" }
