[settings]
experimental = true

[tools]
awscli = "latest"
fd = "latest"
fzf = "latest"
kubectl = "latest"
python = "latest"
ripgrep = "latest"
starship = "latest"
terraform = "latest"
terramate = "latest"
uv = "latest"
yq = "latest"
usage = "latest"
"conda:mosh" = "latest"
gh = "latest"
opencode = "latest"
lazygit = "latest"
bat = "latest"
node = "26.3.0"
markdownlint-cli2 = "0.20.0"
delta = "latest"
pulumi = "3.232.0"
jj = "0.40.0"
"github:amber-lang/amber" = "0.6.0-alpha"
"npm:@earendil-works/pi-coding-agent" = "0.79.2"
neovim = "0.12.3"
television = "0.15.8"

[tools.tmux]
version = "latest" 
install_env = { TEST = "what", TMUX_EXTRA_CONFIGURE_OPTIONS = "--enable-utf8proc" }
