[settings]
experimental = true

[tools]
awscli = "latest"
fd = "latest"
fzf = "0.74.3"
kubectl = "latest"
python = "latest"
ripgrep = "latest"
starship = "latest"
terraform = "latest"
terramate = "latest"
uv = "latest"
yq = "latest"
usage = "latest"
"conda:mosh" = "latest"
gh = "2.98.0"
lazygit = "latest"
bat = "latest"
node = "26.3.0"
markdownlint-cli2 = "0.20.0"
delta = "latest"
pulumi = "3.232.0"
jj = "0.40.0"
"github:amber-lang/amber" = "0.6.0-alpha"
"npm:@earendil-works/pi-coding-agent" = "0.84.2"
"github:ogulcancelik/herdr" = "0.8.0"
neovim = "0.12.5"
television = "0.15.8"
aube = "1.26.0"
"github:can1357/oh-my-pi" = "18.0.5"
"mimiskelda:sessionizer" = { version = "latest" }
"aqua:ogulcancelik/herdr" = "latest"
watchexec = "latest"
