[metadata]
name = "branches"
description = "Lists branches and workspaces"
requirements = ["sessionizer"]

[source]
command = "sessionizer branches list"
no_sort = true
frecency = true

[keybindings]
enter = "actions:enter"

[actions.enter]
description = "Switch to branch, creates worktree in bare checkouts"
command = "sessionizer actions branch-enter {split: :-1}"
mode = "execute"
