[metadata]
name = "workspaces"
description = "Lists and interacts with workspaces"
requirements = ["sessionizer"]

[source]
command = "sessionizer workspaces list"
no_sort = true
frecency = false

[keybindings]
enter = "actions:bare"
ctrl-b = "actions:bare"
ctrl-o = "actions:standard"
ctrl-k = "actions:remove"

[actions.bare]
description = "Enter workspace with bare checkout"
command = "sessionizer actions workspace-enter --bare {split: :-1}"
mode = "execute"

[actions.standard]
description = "Enter workspace (standard checkout)"
command = "sessionizer actions workspace-enter {split: :-1}"
mode = "execute"

[actions.remove]
description = "Removes a workspace"
command = "sessionizer workspace remove {split: :-1}"
mode = "execute"
